# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'weibo(swift)' do

pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'SnapKit'

end

target 'weibo(swift)Tests' do

end

target 'weibo(swift)UITests' do

end

